apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kafka
  name: ebs-sc-kafka  # Match this name in KafkaNodePool template
provisioner: ebs.csi.aws.com
parameters:
  type: gp3  # Specify the EBS volume type (e.g., gp2, gp3, io1)
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer